spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: atabayev.elyor0219@gmail.com
    password: gzzv xbdc ztse abkp
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  base-url: http://localhost:8081

jwt:
  secret: "supersecretkeythatshouldbeatleast32byteslong123"

server:
  port: 8081
